Controllers/MotosController.cs
using Avto.Data;
using Avto.Models;
using AutoMapper;

namespace Avto.Controllers;

public class MotosController : BaseController<MotoModel, Moto>
{
    public MotosController(ApplicationDbContext context, IMapper mapper)
        : base(context, mapper)
    {
    }

}

Controllers/OtdelsController.cs
using Avto.Data;
using Avto.Models;
using AutoMapper;

namespace Avto.Controllers;

public class OtdelsController : BaseController<OtdelModel, Otdel>
{
    public OtdelsController(ApplicationDbContext context, IMapper mapper)
        : base(context, mapper)
    {
    }

}

Controllers/PListsController.cs
using Microsoft.EntityFrameworkCore;
using Avto.Data;
using AutoMapper;
using Avto.Models;
using Avto.Services;

namespace Avto.Controllers;

public class PListsController : BaseController<PListModel, PList>
{
    public PListsController(ApplicationDbContext context, IMapper mapper)
        : base(context, mapper)
    {
    }

    protected override IQueryable<PList> ApplyCustomIncludes(IQueryable<PList> dbSet)
    {
        // Customize the includes for this Controller's actions.
        return dbSet
            .Include(pl => pl.Transaks)
            .Include(pl => pl.Moto)
            .Include(pl => pl.Slujitel)
            .Include(pl => pl.Transaks)
                .ThenInclude(t => t.Otdel);
    }

    protected override IQueryable<PList> ApplyCustomSearch(SearchModel searchModel)
    {
        var query = _context.Lists
            .Where(l => l.Data > DateTime.Today.AddYears(-3));

        if (!string.IsNullOrEmpty(searchModel.Number))
            query = query.Where(l => l.Number.Contains(searchModel.Number));

        if (searchModel.From.HasValue)
            query = query.Where(l => l.Data >= ViewService.ToNullableDateTime(searchModel.From.Value));

        if (searchModel.To.HasValue)
            query = query.Where(l => l.Data <= ViewService.ToNullableDateTime(searchModel.To.Value));

        if (!string.IsNullOrEmpty(searchModel.MotoName))
            query = query.Where(l => l.Moto.Name.Contains(searchModel.MotoName));

        if (!string.IsNullOrEmpty(searchModel.MotoNumber))
            query = query.Where(l => l.Moto.Number.Contains(searchModel.MotoNumber));

        if (searchModel.SlujitelId != 0)
            query = query.Where(l => l.Slujitel.Number == searchModel.SlujitelId);

        if (!string.IsNullOrEmpty(searchModel.SlujitelName))
            query = query.Where(l => l.Slujitel.Name.Contains(searchModel.SlujitelName));

        return query;
    }

}

Controllers/SlujiteliController.cs
using Avto.Data;
using Avto.Models;
using AutoMapper;

namespace Avto.Controllers;

public class SlujiteliController : BaseController<SlujitelModel, Slujitel>
{
    public SlujiteliController(ApplicationDbContext context, IMapper mapper)
        : base(context, mapper)
    {
    }

}

Controllers/TransaksController.cs
using AutoMapper;
using Avto.Data;
using Avto.Models;
using Avto.Services;
using Microsoft.EntityFrameworkCore;

namespace Avto.Controllers;

public class TransaksController : BaseController<TransakModel, Transak>
{
    public TransaksController(ApplicationDbContext context, IMapper mapper)
        : base(context, mapper)
    {
    }

    protected override IQueryable<Transak> ApplyCustomIncludes(IQueryable<Transak> dbSet)
    {
        return dbSet.
            Include(t => t.PList)
                .ThenInclude(pl => pl.Moto)
            .Include(t => t.PList)
                .ThenInclude(pl => pl.Slujitel)
            .Include(t => t.Otdel);
    }

    protected override IQueryable<Transak> ApplyCustomSearch(SearchModel searchModel)
    {
        var query = _context.Transaks
            .Where(l => l.PList.Data > DateTime.Today.AddYears(-1));

        if (!string.IsNullOrEmpty(searchModel.Number))
            query = query.Where(l => l.PList.Number.Contains(searchModel.Number));

        if (searchModel.From.HasValue)
            query = query.Where(l => l.PList.Data >= ViewService.ToNullableDateTime(searchModel.From.Value));

        if (searchModel.To.HasValue)
            query = query.Where(l => l.PList.Data <= ViewService.ToNullableDateTime(searchModel.To.Value));

        if (!string.IsNullOrEmpty(searchModel.MotoName))
            query = query.Where(l => l.PList.Moto.Name.Contains(searchModel.MotoName));

        if (!string.IsNullOrEmpty(searchModel.MotoNumber))
            query = query.Where(l => l.PList.Moto.Number.Contains(searchModel.MotoNumber));

        if (!string.IsNullOrEmpty(searchModel.SlujitelName))
            query = query.Where(l => l.PList.Slujitel.Name.Contains(searchModel.SlujitelName));

        if (!string.IsNullOrEmpty(searchModel.Otdel))
            query = query.Where(t => t.Otdel.Name.Contains(searchModel.Otdel));

        return query;
    }
}

Views/Transaks/Delete.cshtml
@model TransakModel

@Html.Partial("_Head", Model)
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OtdelId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OtdelId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KmId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KmId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KmKm)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KmKm)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TekushtaData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TekushtaData)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User)
        </dd>
    </dl>
@Html.Partial("_DeleteFoot", Model)

Views/Transaks/Edit.cshtml
@model TransakModel
@Html.Partial("_Head", Model)
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="OtdelId" class="control-label"></label>
                <input asp-for="OtdelId" class="form-control" />
                <span asp-validation-for="OtdelId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KmId" class="control-label"></label>
                <input asp-for="KmId" class="form-control" />
                <span asp-validation-for="KmId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KmKm" class="control-label"></label>
                <input asp-for="KmKm" class="form-control" />
                <span asp-validation-for="KmKm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Запази" class="btn btn-primary" />
            </div>
        </form>
@Html.Partial("_EditFoot", Model)

Views/Transaks/Index.cshtml
@model IEnumerable<TransakModel>
<h1>@ViewData["Title"]</h1>
@await Component.InvokeAsync("Search")
@{
    int count = 0;
}
<table class="table">
    <thead>
        <tr>
            <th>№</th>
            <th asp-display-name-for="@Model.First().PListId"></th>
            <th asp-display-name-for="@Model.First().Data"></th>
            <th asp-display-name-for="@Model.First().Moto.NameNumber"></th>
            <th asp-display-name-for="@Model.First().Slujitel.Name"></th>
            <th>@Html.DisplayNameFor(model => model.Otdel)</th>
            <th>@Html.DisplayNameFor(model => model.KmId)</th>
            <th>@Html.DisplayNameFor(model => model.KmKm)</th>
            <th>Литри</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@(((ViewData["Search"] as SearchModel).Page - 1) * 100 + ++count)</td>
                <td><a asp-controller="PLists" asp-action="Edit" asp-route-id="@item.PListId">@item.PListNumber</a></td>
                <td>@item.Data?.ToString("dd.MM.yyyy")</td>
                <td><a asp-controller="Motos" asp-action="Edit" asp-route-id="@item.Moto.Id">@item.Moto.NameNumber</a></td>
                <td><a asp-controller="Slujiteli" asp-action="Edit" asp-route-id="@item.Slujitel.Id">@item.Slujitel.Name</a></td>
                <td><a asp-controller="Otdels" asp-action="Edit" asp-route-id="@item.OtdelId">@item.Otdel</a></td>
                <td asp-display-for="@item.KmId"></td>
                <td asp-display-for="@item.KmKm"></td>
                <td asp-display-for="@item.Litres"></td>
            </tr>
        }
    </tbody>
</table>

<partial name="_Pager" />